language: android
android:
  components:
    - tools
    - platorm-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support

script:
  - ./gradlew build connectedCheck