language: android

jdk: oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2

before_install:
- yes | sdkmanager "platforms;android-27"

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-support
    - extra-android-m2repository

branches:
  only:
    - master

script:
    - ./gradlew :recycler-view-divider:build --continue --stacktrace
    - ./gradlew :sample:sample-java:assembleLocal --continue -s
    - ./gradlew :sample:sample-kotlin:assembleLocal --continue -s

sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache